set nocompatible

syntax enable
filetype plugin indent on
set number relativenumber
set visualbell

set encoding=utf-8

set ts=4
set sw=4
set softtabstop=4
set expandtab

set laststatus=2

set showmode
set showcmd
set showmatch

set t_Co=256
set background=dark

set list
